### ISSUE TITLE
No icon shown in Add-ons Manager

### ISSUE THREAD

**Issue by Keith94** [nicofrand/keepintab#1]
![image](https://user-images.githubusercontent.com/5490615/31268031-69538816-aa2f-11e7-84ae-8322390829b8.png)

**Comment by nicofrand** [comment]
Thank you ! I noticed it too but I don't know why that would occur. I did provide the icon as stated in the documentation…

Il' try to get some help on IRC and keep you posted.

**Comment by nicofrand** [comment]
I believe it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1203521.

On beta it also appears for half a second (unless the devtools are open) before disappearing.
It appears in the details though.

**Comment by Keith94** [comment]
Hmm, I replaced icon.svg with [png version](https://addons.cdn.mozilla.net/user-media/addon_icons/842/842437-64.png) and it works as expected.

![image](https://user-images.githubusercontent.com/5490615/31269975-61cb7286-aa37-11e7-8c40-f0d32517aa14.png)

Maybe there is a problem with your svg file? I tried another add-on's svg and it also works, for example:
https://github.com/eoger/tabcenter-redux/blob/master/src/icons/tabcenter.svg?short_path=a1956af

**Comment by nicofrand** [comment]
I modified the SVG to make it W3C valid and uploaded a new version but it does not work…
Adding it through about:debugging always works, I'm lost…

**Comment by nicofrand** [comment]
I found a related issue on Firefox bugtracker : https://bugzilla.mozilla.org/show_bug.cgi?id=1376518

**Comment by Keith94** [comment]
Oh thanks for finding that, I didn't realize it was a bug in Firefox. I guess this can be closed.
